### ISSUE TITLE
Powerpoint in Git?

### ISSUE THREAD

**Issue by Vindaar** [pbielefeldt/praesentationen_in_git#1]
Nee, also das halte ich für fraglich! 

Natürlich dürfen nur mit Freier Software entworfene Präsentationen mit Git verwaltet werden!

**Comment by pbielefeldt** [comment]
Mit `.fodp` scheint das tatsächlich zu gehen. Ich probier's noch mal weiter. Und klar wird das nur mit freelibrewokeOffice getestet!
